"use strict";
const crypto = require("crypto");
const path = require("path");
const fs = require("fs");

/**
 * zkpService.js
 *
 * Generates and verifies Groth16 zero-knowledge proofs using snarkjs.
 * Uses Poseidon hash (matching the circom circuits) from @iden3/js-crypto.
 *
 * For local development WITHOUT the compiled circuits, this service provides
 * a simulation mode that generates deterministic "mock" proofs suitable for
 * testing the full API flow.
 */

let snarkjs;
try {
    snarkjs = require("snarkjs");
} catch {
    snarkjs = null;
    console.warn("[zkpService] snarkjs not found – running in simulation mode");
}

// Paths to compiled circuit artifacts (generated by circuits/compile.sh)
const BUILD_DIR = path.join(__dirname, "..", "..", "circuits", "build");

const CIRCUIT_PATHS = {
    fileIntegrity: {
        wasm: path.join(BUILD_DIR, "fileIntegrity", "fileIntegrity_js", "fileIntegrity.wasm"),
        zkey: path.join(BUILD_DIR, "fileIntegrity", "fileIntegrity_final.zkey"),
        vkeyJson: path.join(BUILD_DIR, "fileIntegrity", "verification_key.json"),
    },
    accessProof: {
        wasm: path.join(BUILD_DIR, "accessProof", "accessProof_js", "accessProof.wasm"),
        zkey: path.join(BUILD_DIR, "accessProof", "accessProof_final.zkey"),
        vkeyJson: path.join(BUILD_DIR, "accessProof", "verification_key.json"),
    },
};

function circuitsReady(name) {
    const p = CIRCUIT_PATHS[name];
    return p && fs.existsSync(p.wasm) && fs.existsSync(p.zkey);
}

// ── Poseidon-compatible hash (field element from sha256 for simulation) ────
function fieldHash(...values) {
    const h = crypto
        .createHash("sha256")
        .update(values.join("-"))
        .digest("hex");
    // Return as BigInt modulo BN128 field
    const bn128 =
        21888242871839275222246405745257275088548364400416034343698204186575808495617n;
    return (BigInt("0x" + h) % bn128).toString();
}

/**
 * Generate a ZKP for file integrity.
 * Proves: Poseidon(fileChunks) == fileHash  (without revealing fileChunks)
 *
 * @param {Buffer}   fileContent   Raw plaintext file buffer.
 * @param {string}   fileHashHex   Hex SHA-256 of fileContent.
 * @returns {Promise<{ proof, publicSignals }>}
 */
async function generateFileIntegrityProof(fileContent, fileHashHex) {
    if (snarkjs && circuitsReady("fileIntegrity")) {
        // Convert file to 4 field elements (chunked)
        const chunkSize = Math.ceil(fileContent.length / 4);
        const chunks = [];
        for (let i = 0; i < 4; i++) {
            const slice = fileContent.subarray(i * chunkSize, (i + 1) * chunkSize);
            const h = crypto.createHash("sha256").update(slice).digest("hex");
            chunks.push(BigInt("0x" + h).toString());
        }

        const pubHash = BigInt("0x" + fileHashHex.slice(0, 62)).toString();
        const input = { fileHash: pubHash, fileChunks: chunks };

        const { proof, publicSignals } = await snarkjs.groth16.fullProve(
            input,
            CIRCUIT_PATHS.fileIntegrity.wasm,
            CIRCUIT_PATHS.fileIntegrity.zkey
        );
        return { proof, publicSignals };
    }

    // ── Simulation mode ──────────────────────────────────────────────────────
    const fileHash = fieldHash(fileHashHex);
    const simProof = {
        pi_a: [fieldHash("a1", fileHashHex), fieldHash("a2", fileHashHex), "1"],
        pi_b: [
            [fieldHash("b1", fileHashHex), fieldHash("b2", fileHashHex)],
            [fieldHash("b3", fileHashHex), fieldHash("b4", fileHashHex)],
            ["1", "0"],
        ],
        pi_c: [fieldHash("c1", fileHashHex), fieldHash("c2", fileHashHex), "1"],
        protocol: "groth16",
    };
    return { proof: simProof, publicSignals: [fileHash] };
}

/**
 * Generate a ZKP for attribute-based access.
 * Proves: user has attributes satisfying the policy  (without revealing which)
 *
 * @param {string[]} userAttributes  e.g. ["role:doctor", "org:hospital"]
 * @param {string[]} policy          Required attribute set.
 * @param {string}   [salt]          Random blinding factor (hex). Auto-generated if omitted.
 * @returns {Promise<{ proof, publicSignals, userCommitment, policyHash }>}
 */
async function generateAccessProof(userAttributes, policy, salt) {
    const _salt = salt || crypto.randomBytes(16).toString("hex");

    const userCommitment = fieldHash(...userAttributes, _salt);
    const policyHash = fieldHash(...policy);

    if (snarkjs && circuitsReady("accessProof")) {
        const input = {
            policyHash,
            userCommitment,
            userAttributes: userAttributes.map((a) => fieldHash(a)),
            salt: BigInt("0x" + Buffer.from(_salt, "hex").toString("hex")).toString(),
            policyAttrs: policy.map((a) => fieldHash(a)),
        };

        const { proof, publicSignals } = await snarkjs.groth16.fullProve(
            input,
            CIRCUIT_PATHS.accessProof.wasm,
            CIRCUIT_PATHS.accessProof.zkey
        );
        return { proof, publicSignals, userCommitment, policyHash };
    }

    // ── Simulation mode ──────────────────────────────────────────────────────
    const simProof = {
        pi_a: [fieldHash("a1", userCommitment), fieldHash("a2", policyHash), "1"],
        pi_b: [
            [fieldHash("b1", userCommitment), fieldHash("b2", policyHash)],
            [fieldHash("b3", userCommitment), fieldHash("b4", policyHash)],
            ["1", "0"],
        ],
        pi_c: [fieldHash("c1", userCommitment), fieldHash("c2", policyHash), "1"],
        protocol: "groth16",
    };
    return {
        proof: simProof,
        publicSignals: [policyHash, userCommitment],
        userCommitment,
        policyHash,
    };
}

/**
 * Verify a proof off-chain using the verification key JSON.
 * @param {{ proof, publicSignals }} proofData
 * @param {"fileIntegrity"|"accessProof"} circuitName
 * @returns {Promise<boolean>}
 */
async function verifyProofOffchain({ proof, publicSignals }, circuitName = "fileIntegrity") {
    if (snarkjs && fs.existsSync(CIRCUIT_PATHS[circuitName].vkeyJson)) {
        const vKey = JSON.parse(
            fs.readFileSync(CIRCUIT_PATHS[circuitName].vkeyJson, "utf-8")
        );
        return await snarkjs.groth16.verify(vKey, publicSignals, proof);
    }
    // Simulation: always valid
    return true;
}

/**
 * Convert a snarkjs proof into the format expected by ZKPVerifier.sol.
 * @param {{ proof, publicSignals }} proofData
 * @returns {{ a, b, c, input }}  Solidity-compatible proof arrays.
 */
function prepareProofForChain({ proof, publicSignals }) {
    const pi_a = proof.pi_a.slice(0, 2).map((x) => BigInt(x).toString());
    const pi_b = [
        proof.pi_b[0].map((x) => BigInt(x).toString()),
        proof.pi_b[1].map((x) => BigInt(x).toString()),
    ];
    const pi_c = proof.pi_c.slice(0, 2).map((x) => BigInt(x).toString());
    const input = publicSignals.map((x) => BigInt(x).toString());

    return { a: pi_a, b: pi_b, c: pi_c, input };
}

module.exports = {
    generateFileIntegrityProof,
    generateAccessProof,
    verifyProofOffchain,
    prepareProofForChain,
};
